version: 2
# updates:
#   - package-ecosystem: "npm"
#     directory: "/"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#       time: "06:00"
#       timezone: "Europe/Zurich"
#     commit-message:
#       prefix: "Update"
#     groups:
#       dependencies:
#         patterns:
#           - "*"
