module.exports = {
  extends: "stylelint-config-standard",
  plugins: ["stylelint-order"],
  rules: {
    "length-zero-no-unit": [true, { ignore: ["custom-properties"] }],
    "property-no-vendor-prefix": null,
    "custom-property-pattern": null,
    "selector-class-pattern": null,
    "selector-id-pattern": null,
    "at-rule-no-unknown": null,
    "no-descending-specificity": null,
    "order/properties-order": [
      [
        {
          groupName: "display",
          properties: [
            "content",
            "appearance",
            "position",
            "top",
            "right",
            "bottom",
            "left",
            "z-index",
            "display",
            "flex",
            "flex-direction",
            "flex-basis",
            "flex-flow",
            "flex-grow",
            "flex-shrink",
            "flex-wrap",
            "align-content",
            "align-items",
            "justify-content",
            "justify-items",
          ],
        },
        {
          groupName: "grid",
          properties: [
            "grid",
            "grid-area",
            "grid-template",
            "grid-template-areas",
            "grid-template-rows",
            "grid-template-columns",
            "grid-row",
            "grid-row-start",
            "grid-row-end",
            "grid-column",
            "grid-column-start",
            "grid-column-end",
            "grid-auto-rows",
            "grid-auto-columns",
            "grid-auto-flow",
            "grid-gap",
            "grid-row-gap",
            "grid-column-gap",
            "gap",
          ],
        },
        {
          groupName: "dimensions",
          properties: [
            "width",
            "max-width",
            "min-width",
            "height",
            "max-height",
            "min-height",
          ],
        },
        {
          groupName: "margin",
          properties: [
            "margin",
            "margin-top",
            "margin-right",
            "margin-bottom",
            "margin-left",
            "margin-inline",
            "margin-inline-start",
            "margin-inline-end",
            "margin-block",
            "margin-block-start",
            "margin-block-end",
          ],
        },
        {
          groupName: "padding",
          properties: [
            "padding",
            "padding-top",
            "padding-right",
            "padding-bottom",
            "padding-left",
            "padding-inline",
            "padding-inline-start",
            "padding-inline-end",
            "padding-block",
            "padding-block-start",
            "padding-block-end",
          ],
        },
        {
          groupName: "border",
          properties: [
            "box-sizing",
            "border",
            "border-width",
            "border-style",
            "border-color",
            "border-top",
            "border-right",
            "border-bottom",
            "border-left",
            "border-top-width",
            "border-right-width",
            "border-bottom-width",
            "border-left-width",
            "border-top-style",
            "border-right-style",
            "border-bottom-style",
            "border-left-style",
            "border-top-color",
            "border-right-color",
            "border-bottom-color",
            "border-left-color",
            "border-inline",
            "border-inline-start",
            "border-inline-end",
            "border-block",
            "border-block-start",
            "border-block-end",
            "border-radius",
            "outline",
            "box-shadow",
          ],
        },
        {
          groupName: "background",
          properties: ["background", "background-color", "background-image"],
        },
        {
          groupName: "font",
          properties: [
            "font",
            "font-family",
            "font-size",
            "font-style",
            "font-weight",
            "line-height",
            "color",
            "text-decoration",
            "font-smoothing",
          ],
        },
      ],
      {
        unspecified: "bottom",
      },
    ],
  },
};
